version: "3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chipetpet
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  back-end:
    image: chipetpetbackend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./ChiPetPetBackend:/code

  front-end:
    image: chipetpetfrontend
    ports:
      - "5173:5173"
    depends_on:
      - back-end
    volumes:
      # - ./ChiPetPetFrontend:/code
      - ./ChiPetPetFrontend/src:/app/src