version: "3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chipetpet
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  back-end:
    image: chipetpetbackend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ChiPetPetBackEnd:/code

  front-end:
    image: chipetpetfrontend
    ports:
      - "5173:5173"
    depends_on:
      - back-end
    volumes:
      - ./ChiPetPetFrontEnd/src:/app/src
